# Generated by Django 5.2.7 on 2026-02-27 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_perfilempresa_tempo_medio_retirada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Loja')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Foto de Capa')),
                ('cor_principal', models.CharField(default='#E91E63', max_length=7, verbose_name='Cor Principal (Botões e Detalhes)')),
                ('cor_fundo', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor de Fundo (Tema Clean/Dark)')),
                ('direcao_layout', models.CharField(choices=[('vertical', 'Vertical (Rolagem padrão para baixo)'), ('horizontal', 'Horizontal (Rolagem lateral por categoria)')], default='vertical', max_length=15, verbose_name='Direção do Layout')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customizacao', to='empresas.perfilempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Customização da Empresa',
                'verbose_name_plural': 'Customizações das Empresas',
            },
        ),
    ]
