# Generated by Django 5.2.7 on 2026-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_pendente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Assinatura'), ('APROVADO', 'Assinatura Confirmada (Benefício Liberado)'), ('CANCELADO', 'Cancelado/Expirado')], default='PENDENTE', max_length=20)),
                ('tipo_beneficio', models.CharField(choices=[('MES_GRATIS', '1 Mês Grátis (Indicador é Empresa)'), ('COMISSAO', 'R$ 50,00 (Indicador é Pessoa Física)')], editable=False, max_length=20)),
                ('data_indicacao', models.DateTimeField(auto_now_add=True)),
                ('data_conversao', models.DateTimeField(blank=True, help_text='Data em que a assinatura foi paga', null=True)),
            ],
        ),
    ]
