# Generated by Django 5.2.7 on 2025-12-20 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_pendente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira_parceiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_indicador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Assinatura'), ('APROVADO', 'Assinatura Confirmada (Benefício Liberado)'), ('CANCELADO', 'Cancelado/Expirado')], default='PENDENTE', max_length=20)),
                ('tipo_beneficio', models.CharField(choices=[('MES_GRATIS', '1 Mês Grátis (Indicador é Empresa)'), ('COMISSAO', 'R$ 50,00 (Indicador é Pessoa Física)')], editable=False, max_length=20)),
                ('data_indicacao', models.DateTimeField(auto_now_add=True)),
                ('data_conversao', models.DateTimeField(blank=True, help_text='Data em que a assinatura foi paga', null=True)),
                ('indicado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicacao_recebida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Indicado')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_feitas', to='assinatura_indicacao.codigoindicador')),
            ],
        ),
    ]
