# Generated by Django 5.2.7 on 2026-03-08 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinatura_indicacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carteiraparceiro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira_parceiro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codigoindicador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_indicador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='indicado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicacao_recebida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Indicado'),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_feitas', to='assinatura_indicacao.codigoindicador'),
        ),
    ]
