# Generated by Django 5.2.7 on 2026-03-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade')),
                ('observacao', models.TextField(blank=True, help_text='Observação específica para este item (ex: retirar cebola).', null=True, verbose_name='observação')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedidos', to='catalogo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(blank=True, help_text='Data e hora agendada para entrega, se aplicável.', null=True, verbose_name='data agendamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('valor_taxa_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='taxa de entrega cobrada')),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('credit', 'Cartão de Crédito'), ('money', 'Dinheiro')], default='pix', max_length=20, verbose_name='método de pagamento')),
                ('troco_para', models.DecimalField(blank=True, decimal_places=2, help_text='Quanto dinheiro o cliente vai entregar (para calcular troco).', max_digits=10, null=True, verbose_name='troco para')),
                ('bandeira_cartao', models.CharField(blank=True, help_text='Qual a bandeira do cartão para levar a maquininha correta.', max_length=50, verbose_name='bandeira do cartão')),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('EM_ANDAMENTO', 'Em Andamento'), ('PRONTO', 'Pronto para Entrega'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=50, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=100, verbose_name='código de rastreio')),
                ('bairro_logistica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.bairroentrega', verbose_name='região de logística')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('-criado_em',),
            },
        ),
    ]
