# Generated by Django 5.2.7 on 2025-12-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('credit', 'Cartão de Crédito')], default='pix', max_length=20, verbose_name='método de pagamento'),
        ),
    ]
