# Generated by Django 5.2.7 on 2025-12-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, help_text='Data e hora agendada para entrega, se aplicável.', null=True, verbose_name='data agendamento'),
        ),
    ]
