# Generated by Django 5.2.7 on 2025-12-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bandeira_cartao',
            field=models.CharField(blank=True, help_text='Qual a bandeira do cartão para levar a maquininha correta.', max_length=50, verbose_name='bandeira do cartão'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='troco_para',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quanto dinheiro o cliente vai entregar (para calcular troco).', max_digits=10, null=True, verbose_name='troco para'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('credit', 'Cartão de Crédito'), ('money', 'Dinheiro')], default='pix', max_length=20, verbose_name='método de pagamento'),
        ),
    ]
