# Generated by Django 5.2.7 on 2026-02-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_bandeira_cartao_pedido_troco_para_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações gerais do pedido (ex: campainha quebrada, retirar cebola).', verbose_name='observação'),
        ),
    ]
