# Generated by Django 5.2.7 on 2026-02-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='observacao',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observação específica para este item (ex: retirar cebola).', null=True, verbose_name='observação'),
        ),
    ]
