# Generated by Django 5.2.7 on 2026-03-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_rota_entrega'),
        ('pedidos', '0009_remove_pedido_observacao_itempedido_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro_logistica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.bairroentrega', verbose_name='região de logística'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='taxa de entrega cobrada'),
        ),
    ]
