# Generated by Django 5.2.7 on 2026-02-28 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_perfilempresa_tempo_medio_retirada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_pessoal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Folha de Pagamento (R$)')),
                ('gasto_operacional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custos Operacionais (Água, Luz, Net, Aluguel)')),
                ('imposto_pct', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Imposto (%)')),
                ('custo_material_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Custo de Material/Insumos (%)')),
                ('lucro_desejado_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Lucro Desejado (%)')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='empresas.perfilempresa')),
            ],
        ),
    ]
