# Generated by Django 5.2.7 on 2026-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_tributario', models.CharField(choices=[('MEI', 'MEI (Microempreendedor)'), ('SIMPLES', 'Simples Nacional'), ('PRESUMIDO', 'Lucro Presumido'), ('REAL', 'Lucro Real')], default='SIMPLES', max_length=20, verbose_name='Regime Tributário')),
                ('gasto_pessoal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Folha de Pagamento (R$)')),
                ('gasto_operacional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custos Operacionais (Água, Luz, Net, Aluguel)')),
                ('imposto_pct', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Imposto (%)')),
                ('custo_material_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Custo de Material/Insumos (%)')),
                ('lucro_desejado_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Lucro Desejado (%)')),
            ],
        ),
    ]
