# Generated by Django 5.2.7 on 2026-02-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='regime_tributario',
            field=models.CharField(choices=[('MEI', 'MEI (Microempreendedor)'), ('SIMPLES', 'Simples Nacional'), ('PRESUMIDO', 'Lucro Presumido'), ('REAL', 'Lucro Real')], default='SIMPLES', max_length=20, verbose_name='Regime Tributário'),
        ),
    ]
