# Generated by Django 5.2.7 on 2026-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BairroEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Bairro/Região')),
                ('taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Taxa de Entrega (R$)')),
            ],
            options={
                'verbose_name': 'Bairro de Entrega',
                'verbose_name_plural': 'Bairros de Entrega',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_paga_motoboy', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_concluida', models.BooleanField(default=False)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entrega (Pacote)',
                'verbose_name_plural': 'Entregas (Pacotes)',
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Entregador')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF (Login)')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa da Moto')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Taxa Fixa Diária (R$)')),
                ('is_ativo_hoje', models.BooleanField(default=True, verbose_name='Disponível para entregas hoje?')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREPARANDO', 'Preparando (Aguardando na Loja)'), ('EM_ROTA', 'Em Rota de Entrega'), ('CONCLUIDA', 'Concluída')], default='PREPARANDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rota de Entrega',
                'verbose_name_plural': 'Rotas de Entrega',
            },
        ),
    ]
