# Generated by Django 5.2.7 on 2026-03-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_perfilempresa_tempo_medio_retirada'),
    ]

    operations = [
        migrations.CreateModel(
            name='BairroEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Bairro/Região')),
                ('taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Taxa de Entrega (R$)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros_entrega', to='empresas.perfilempresa')),
            ],
            options={
                'verbose_name': 'Bairro de Entrega',
                'verbose_name_plural': 'Bairros de Entrega',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Motoboy')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa da Moto')),
                ('is_ativo_hoje', models.BooleanField(default=True, verbose_name='Disponível para entregas hoje?')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoboys', to='empresas.perfilempresa')),
            ],
            options={
                'verbose_name': 'Motoboy',
                'verbose_name_plural': 'Motoboys',
                'ordering': ['nome'],
            },
        ),
    ]
