# Generated by Django 5.2.7 on 2026-03-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='taxa_fixa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Taxa Fixa Diária (R$)'),
        ),
    ]
