# Generated by Django 5.2.7 on 2026-03-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('logistica', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairroentrega',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros_entrega', to='empresas.perfilempresa'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despacho_logistica', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregadores', to='empresas.perfilempresa'),
        ),
        migrations.AddField(
            model_name='rota',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='empresas.perfilempresa'),
        ),
        migrations.AddField(
            model_name='rota',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='logistica.entregador'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='logistica.rota'),
        ),
    ]
