# Generated by Django 5.2.7 on 2026-03-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_perfilempresa_tempo_medio_retirada'),
        ('logistica', '0002_motoboy_taxa_fixa'),
        ('pedidos', '0009_remove_pedido_observacao_itempedido_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREPARANDO', 'Preparando (Aguardando na Loja)'), ('EM_ROTA', 'Em Rota de Entrega'), ('CONCLUIDA', 'Concluída')], default='PREPARANDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='empresas.perfilempresa')),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='logistica.motoboy')),
            ],
            options={
                'verbose_name': 'Rota de Entrega',
                'verbose_name_plural': 'Rotas de Entrega',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_paga_motoboy', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_concluida', models.BooleanField(default=False)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despacho_logistica', to='pedidos.pedido')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='logistica.rota')),
            ],
            options={
                'verbose_name': 'Entrega (Pacote)',
                'verbose_name_plural': 'Entregas (Pacotes)',
            },
        ),
    ]
