# Generated by Django 5.2.7 on 2026-03-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='longitude'),
        ),
    ]
