# Generated by Django 5.2.7 on 2025-12-19 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_empresa', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='usuário dono')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone_comercial', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Perfil da Empresa',
                'verbose_name_plural': 'Perfis de Empresas',
            },
        ),
    ]
