# Generated by Django 5.2.7 on 2026-03-08 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_empresa', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='usuário dono')),
                ('razao_social', models.CharField(blank=True, max_length=255)),
                ('nome_fantasia', models.CharField(default='Minha Loja', max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('telefone_comercial', models.CharField(blank=True, max_length=20)),
                ('is_aberto', models.BooleanField(default=True, help_text="Se desmarcado, o site mostrará um aviso de 'Fechado' e bloqueará pedidos.", verbose_name='loja aberta agora?')),
                ('horario_funcionamento', models.CharField(default='Segunda a Domingo: 18:00 às 23:00', help_text='Texto exibido no rodapé ou topo do site.', max_length=255, verbose_name='texto do horário')),
                ('endereco_completo', models.TextField(blank=True, help_text='Exibido no rodapé e no contato.', verbose_name='endereço da loja')),
                ('aceita_entrega', models.BooleanField(default=True, verbose_name='Faz Entrega (Delivery)')),
                ('aceita_retirada', models.BooleanField(default=True, verbose_name='Aceita Retirada (Balcão)')),
                ('tempo_medio_entrega', models.CharField(default='40-60 min', max_length=50)),
                ('tempo_medio_retirada', models.CharField(default='30-40 min', max_length=50, verbose_name='Tempo Médio de Retirada')),
                ('taxa_entrega_padrao', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Taxa de Entrega Padrão (R$)')),
                ('pagamento_pix', models.BooleanField(default=True, verbose_name='Aceita PIX')),
                ('pagamento_cartao_credito', models.BooleanField(default=True, verbose_name='Aceita Crédito')),
                ('pagamento_cartao_debito', models.BooleanField(default=True, verbose_name='Aceita Débito')),
                ('pagamento_dinheiro', models.BooleanField(default=True, verbose_name='Aceita Dinheiro')),
                ('chave_pix_pagamento', models.CharField(blank=True, help_text='Chave PIX para o cliente pagar no checkout.', max_length=255, verbose_name='Chave PIX')),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
    ]
