# Generated by Django 5.2.7 on 2025-12-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilempresa',
            options={'verbose_name': 'Configuração da Loja', 'verbose_name_plural': 'Configurações da Loja'},
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='aceita_entrega',
            field=models.BooleanField(default=True, verbose_name='Faz Entrega (Delivery)'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='aceita_retirada',
            field=models.BooleanField(default=True, verbose_name='Aceita Retirada (Balcão)'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='chave_pix_pagamento',
            field=models.CharField(blank=True, help_text='Chave PIX para o cliente pagar no checkout.', max_length=255, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='endereco_completo',
            field=models.TextField(blank=True, help_text='Exibido no rodapé e no contato.', verbose_name='endereço da loja'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='horario_funcionamento',
            field=models.CharField(default='Segunda a Domingo: 18:00 às 23:00', help_text='Texto exibido no rodapé ou topo do site.', max_length=255, verbose_name='texto do horário'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='is_aberto',
            field=models.BooleanField(default=True, help_text="Se desmarcado, o site mostrará um aviso de 'Fechado' e bloqueará pedidos.", verbose_name='loja aberta agora?'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='pagamento_cartao_credito',
            field=models.BooleanField(default=True, verbose_name='Aceita Crédito'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='pagamento_cartao_debito',
            field=models.BooleanField(default=True, verbose_name='Aceita Débito'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='pagamento_dinheiro',
            field=models.BooleanField(default=True, verbose_name='Aceita Dinheiro'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='pagamento_pix',
            field=models.BooleanField(default=True, verbose_name='Aceita PIX'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='taxa_entrega_padrao',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Taxa de Entrega Padrão (R$)'),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='tempo_medio_entrega',
            field=models.CharField(default='40-60 min', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='nome_fantasia',
            field=models.CharField(default='Minha Loja', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
