# Generated by Django 5.2.7 on 2026-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_perfilempresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='tempo_medio_retirada',
            field=models.CharField(default='30-40 min', max_length=50, verbose_name='Tempo Médio de Retirada'),
        ),
    ]
